### ISSUE TITLE
Update/Change Windows SDK

### ISSUE THREAD

**Issue by rodlie** [NatronGitHub/Natron#681]
So, we are starting to reach our limits with the current Windows SDK. The msys2-base we use are now getting too old, and issues related Let's Encrypt [expired](https://www.openssl.org/blog/blog/2021/09/13/LetsEncryptRootCertExpire/) certificate is starting to become a blocker for new SDK installations and GitHub Actions (I have fixed the OpenSSL issue for mingw64 packages, but the core msys2 system can't be fixed), and getting newer software building is also starting to get challenging.

I'm still able to produce binaries and update the sdk, so this is not a blocker for release, but something will need to be done, the faster the better.

Currently I propose to rebase on latest MSYS2 or a (modern) snapshot, but I'm also open for alternatives.

**Comment by rodlie** [comment]
So, Python 3.9 is a no-go(*) on our current Windows SDK. I will need to update MSYS2 to the latest snapshot to get it working. This may introduce other issues, but unless I do this now we will not have Python 3(.9) in the Windows builds.

 (*) Python 3.8+ requires a newer version of mingw-w64, I tried backporting and modifying core mingw headers, but at best I ended up with a broken Python (everything math/date/time related fails), at the worst I broke everything.

I will start building what's needed (OCIO/OIIO/Qt/PySide etc) on the new SDK tomorrow and see how far I get.

**Comment by devernay** [comment]
@rodlie any progress on this? Python 3.7 is OK if it's easier (EOL in June 2023)

**Comment by rodlie** [comment]
MSYS2 and Python go hand in hand, they do [heavy patching](https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-python) (borderline fork), and I need to use the latest MSYS to get latest Python.

I do have MSYS (snapshot from a couple of month ago) with Python 3.9, but there was issues with GCC, so I put that on hold, can check if they have fixed the issues.

Our working SDK only goes to Python 3.6, I tried backporting Python from newer MSYS, but due to all the patches it will not work.

Will dedicate some hours this weekend and try to get something working.

**Comment by rodlie** [comment]
Current SDK issues that needs to be resolved:

- [ ] Loading/Saving project files are slow (Boost?)
- [ ] Python needs to be upgraded
- [ ] Qt5+pyside2 needs to be added
- [ ] MSYS2 must be upgraded (due to Python)

**Comment by rodlie** [comment]
A small update, I was able to build Python 3.7 (with some modifications) on our MSYS2 fork. Will do some tests later today and check that everything works as it should. 

3.8+ is a no-go for now.

**Comment by devernay** [comment]
Py3.7 is OK for 2.5
Qt5 is only required for 2.6

**Comment by rodlie** [comment]
https://github.com/NatronGitHub/Natron/blob/RB-2.5/tools/jenkins/zip-python.sh#L17

No zip file for the Python version I'm using (3.7.12), and why are we downloading a prebuilt Python?

**Comment by devernay** [comment]
we're just using the python39.zip file from that distribution, which avoids having hundreds of python files, and is cross-platform-and-arch.
You could try to build a python37.zip file. I found it difficult to only include the files that were meaningful for an embedded python, so I got it from a binary distrib.

**Comment by rodlie** [comment]
Ok, will find a solution. 

Can probably make a python37.zip during build of Python and bundle it with the mingw package.

**Comment by devernay** [comment]
https://www.python.org/ftp/python/3.7.9/ has an embedded distribution.
Here's the doc for that zip file: https://docs.python.org/3.7/using/windows.html#the-embeddable-package
It works on macOS and linux too.
There's probably a script that builds it in the python distrib, but I couldn't find it.

**Comment by devernay** [comment]
alternatively, you can do it the old way and copy the py and pyc from the installed python, but it's prone to error (unless you want to include everything).

**Comment by rodlie** [comment]
The zip is fixed, I generate it after the python build and bundle it with the mingw package.

But, pip (``"${NATRON_PYTHON}" get-pip.py``) seems to have issues:
```
Collecting pip
  Using cached pip-21.3.1-py3-none-any.whl (1.7 MB)
Collecting setuptools
  Using cached setuptools-60.5.0-py3-none-any.whl (958 kB)
Collecting wheel
  Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel, setuptools, pip
  WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: C:\msys64-20180531\home\Natron\workspace\tmp64\tmp_deploy\Natron-RB-2.5-202201161340-8fcb2ff-Windows-x86_64\include\python3.7m\wheel
  sysconfig: C:\msys64-20180531\home\Natron\workspace\tmp64\tmp_deploy\Natron-RB-2.5-202201161340-8fcb2ff-Windows-x86_64\include\python3.7\wheel
  WARNING: Additional context:
  user = False
  home = None
  root = None
  prefix = None
ERROR: Exception:
Traceback (most recent call last):
  File "C:\msys64-20180531\tmp\tmp81pjzku6\pip.zip\pip\_internal\cli\base_command.py", line 164, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\msys64-20180531\tmp\tmp81pjzku6\pip.zip\pip\_internal\cli\req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "C:\msys64-20180531\tmp\tmp81pjzku6\pip.zip\pip\_internal\commands\install.py", line 413, in run
    pycompile=options.compile,
  File "C:\msys64-20180531\tmp\tmp81pjzku6\pip.zip\pip\_internal\req\__init__.py", line 81, in install_given_reqs
    pycompile=pycompile,
  File "C:\msys64-20180531\tmp\tmp81pjzku6\pip.zip\pip\_internal\req\req_install.py", line 810, in install
    requested=self.user_supplied,
  File "C:\msys64-20180531\tmp\tmp81pjzku6\pip.zip\pip\_internal\operations\install\wheel.py", line 737, in install_wheel
    requested=requested,
  File "C:\msys64-20180531\tmp\tmp81pjzku6\pip.zip\pip\_internal\operations\install\wheel.py", line 646, in _install_wheel
    generated_console_scripts = maker.make_multiple(scripts_to_generate)
  File "C:\msys64-20180531\tmp\tmp81pjzku6\pip.zip\pip\_vendor\distlib\scripts.py", line 428, in make_multiple
    filenames.extend(self.make(specification, options))
  File "C:\msys64-20180531\tmp\tmp81pjzku6\pip.zip\pip\_internal\operations\install\wheel.py", line 427, in make
    return super().make(specification, options)
  File "C:\msys64-20180531\tmp\tmp81pjzku6\pip.zip\pip\_vendor\distlib\scripts.py", line 417, in make
    self._make_script(entry, filenames, options=options)
  File "C:\msys64-20180531\tmp\tmp81pjzku6\pip.zip\pip\_vendor\distlib\scripts.py", line 317, in _make_script
    self._write_script(scriptnames, shebang, script, filenames, ext)
  File "C:\msys64-20180531\tmp\tmp81pjzku6\pip.zip\pip\_vendor\distlib\scripts.py", line 247, in _write_script
    launcher = self._get_launcher('t')
  File "C:\msys64-20180531\tmp\tmp81pjzku6\pip.zip\pip\_vendor\distlib\scripts.py", line 396, in _get_launcher
    raise ValueError(msg)
ValueError: Unable to find resource t64.exe in package pip._vendor.distlib

```

EDIT: might have found a solution.

**Comment by rodlie** [comment]
Ok, so I can't use pip to install stuff that needs compiling, pip want MSVC (as with upstream Python).

I probably need to package (MINGW-packages) pip and/or wheel, setuptools, qtpy, six, psutil.

**Comment by devernay** [comment]
Are you certain your python37.zip contains *just* what's necessary, not more?
Does it contain *all* that's necessary? pyc and py?
 
Did you compare with a python37.zip from an official distribution?

**Comment by devernay** [comment]
I think it would be more reasonable to have a continuously updated mingw, just like we do on Linux (we use GCC 11) and macOS (clang 11 or 12, depending on the OS). It's a bit of a concern that your toolchain doesn't compile Python 3.8, which is already 3 years old.

Shouldn't you work on this rather than doing all those fixups (and there are probably more to come)?

**Comment by devernay** [comment]
pip shouldn't require a compiler for stuff that is provided in wheels, but the official wheels probably rely on having the MSVC++ redistributable

**Comment by rodlie** [comment]
> Are you certain your python37.zip contains just what's necessary, not more?

Yes, it's identical to the offical python37.zip.

> I think it would be more reasonable to have a continuously updated mingw

That's the plan for the next SDK.

> Shouldn't you work on this rather than doing all those fixups (and there are probably more to come)?

Ok.

> It's a bit of a concern that your toolchain doesn't compile Python 3.8, which is already 3 years old.

Python on MinGW/MSYS2 is a [fork](https://github.com/msys2-contrib/cpython-mingw), they have a ton of patches, 3.8+ has patches against a newer MinGW so I can't build it.

> pip shouldn't require a compiler for stuff that is provided in wheels, but the official wheels probably rely on having the MSVC++ redistributable

I got pip working, but some of the packages installed through pip required building(?), and they fail since we don't use/have MSVC.

```
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
```

**Comment by rodlie** [comment]
Dropping MinGW would probably solve several issues, but moving to MSVC would require a lot of work.

https://bugs.python.org/issue45538

**Comment by devernay** [comment]
I'm not saying to switch to MSVC, but at least keeping the toolchain up-to-date.

Did you install MSVC so that pip can compile the required packages? I'm a bit surprised that those don't have wheels, but maybe it's pyside? Did you check which ones are being compiled and why?

C/C++ uses a standard ABI, so there shouldn't be issues using MSVC-compiled PyPi wheels with a mingw-compiled Natron

**Comment by rodlie** [comment]
> Did you install MSVC so that pip can compile the required packages?

No, I don't have enough space on the build machine for MSVC. Can setup a new machine or find a new disk.

> Did you check which ones are being compiled and why?

Not in front of that computer now, but it was after wheel and setuptools. So either qtpy, six or psutil. https://github.com/NatronGitHub/Natron/blob/RB-2.5/tools/jenkins/build-Windows-installer.sh#L442

**Comment by devernay** [comment]
qtpy is not arch-specific: https://pypi.org/project/QtPy/1.11.2/#files

six too: https://pypi.org/project/six/#files

could be psutil, but it has a cp37 amd64 wheel: https://pypi.org/project/psutil/#files

**Comment by rodlie** [comment]
I could build it? msys2 has a pkgbuild for it (psutil) https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-python-psutil

**Comment by devernay** [comment]
yes or you could skip it for now. It's one of the few packages that come pre-installed in Nuke, which is why I selected it, but maybe not many users will miss it. I can see it being useful, though.

For the MSVC build, it's also probably better to wait for Qt5/Natron 2.6 (vcpkg has a qt5 package https://vcpkg.info/port/qt5)

psutil can wait for the Qt5 version

**Comment by rodlie** [comment]
Just tested pip at work where I have VS2019 (also tested VS2015). Anything that needs building will fail (VC is not supported by this module). This is a known issue with using cpython-mingw.

> For the MSVC build, it's also probably better to wait for Qt5/Natron 2.6 (vcpkg has a qt5 package https://vcpkg.info/port/qt5)

Qt5 on MSVC is easy to build anyway. MSVC will require changes, build issues in Natron will need to be fixed, the build scripts must be re-written etc.

**Comment by devernay** [comment]
You should ask for help (twitter, pixls.us, FB) to make that VS build happen. VS2019 + vcpkg seems like a more durable and versatile solution than mingw + msys2

**Comment by rodlie** [comment]
I have a working RB-2.5, but I used the MinGW packages for setuptools, pip etc from MSYS2, as they have patches to make it work against cpython-mingw (the fork we use of Python).

> VS2019 + vcpkg seems like a more durable and versatile solution than mingw + msys2

I agree, but moving to MSVC will take time (unless I get help). Not something realistic for RB-2.5.

**Comment by BigRoy** [comment]
Any progress on getting onto more recent versions of Qt? It seems that Natron 2.5.0 still uses `PySide` instead of `PySide2` or even `PySide6`.

**Comment by rodlie** [comment]
> It seems that Natron 2.5.0 still uses PySide instead of PySide2 or even PySide6

Natron 2.5 is Qt4. Natron 2.6 will have Qt5.
