### ISSUE TITLE
Doesn't start 

### ISSUE THREAD

**Issue by marillat** [NatronGitHub/Natron#808]
### Make sure to follow our issue report guidelines

- [ ] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [X] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) or in a [pull request](https://github.com/NatronGitHub/Natron/pulls) already (go search for it and dig around a little bit!)
- [X] This bug is reproducible

### Natron version

Natron 2.5

### Operating system

Linux 5.18.3 amd64

### Did you install Natron using the official installer?

- [ ] Yes, I used the official installer
- [ ] No, I installed from a binary archive
- [X] No, I compiled Natron from sources
- [ ] No, I installed Natron via another method

### Custom installation path

/usr/bin

### What were you trying to do?

I start Natron without command line options.

### What did you expect to happen? What happened instead?

Natron crash.

### Step-by-step reproduction instructions

1. Start Natron

### Additional details

```
$ Natron
Natron Version 2.5
(C) 2018-2022 The Natron developers
(C) 2013-2018 INRIA and Alexandre Gauthier-Foichat
>>>Use the --help or -h option to print usage.<<<
args:
* Command-line parsing results:
clearCacheOnLaunch: false
clearOpenFXCacheOnLaunch: false
useDefaultSettings: false
isBackground: false
isInterpreterMode: false
enableRenderStats: false
exportDocsPath: ""
ipcPipe: ""
defaultOnProjectLoadedScript: ""
settingCommands:
pythonCommands:
writers:
readers:
atLeastOneOutput: false
filename: ""
rangeSet: false
frameRanges:
* End of command-line parsing results.
argv[0] = Natron
keyboard input locale: "fr"
Fontconfig configuration file /usr/bin/../Resources/etc/fonts does not exist, not setting FONTCONFIG_PATH 
"/usr/bin/../lib/python310.zip" does not exist, not added to PYTHONPATH
"/usr/bin/../lib/python3.10/site-packages" does not exist, not added to PYTHONPATH
"/usr/bin/../Plugins" does not exist, not added to PYTHONPATH
Py_SetPythonHome("/usr/bin/..")
PYTHONPATH set to /usr/bin/../lib/python3.10:/usr/bin/../lib/python3.10/lib-dynload
Py_Initialize()
PATH is /home/marillat/bin:/sbin:/usr/sbin:/home/marillat/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/games
PYTHONPATH is /usr/bin/../lib/python3.10:/usr/bin/../lib/python3.10/lib-dynload
PYTHONHOME is (null)
Py_DebugFlag is 0
Py_VerboseFlag is 0
Py_InteractiveFlag is 0
Py_InspectFlag is 0
Py_OptimizeFlag is 0
Py_NoSiteFlag is 0
Py_BytesWarningFlag is 0
Py_FrozenFlag is 0
Py_HashRandomizationFlag is 1
Py_IsolatedFlag is 0
Py_QuietFlag is 0
Py_IgnoreEnvironmentFlag is 0
Py_DontWriteBytecodeFlag is 0
Py_NoUserSiteDirectory is 1
Py_GetProgramName is Natron
Py_GetPrefix is /usr/bin/..
Py_GetExecPrefix is /usr/bin/..
Py_GetProgramFullPath is /usr/bin/Natron
Py_GetPath is /usr/bin/../lib/python3.10:/usr/bin/../lib/python3.10/lib-dynload:/usr/bin/../lib/python310.zip:/usr/bin/../lib/python3.10:/usr/bin/../lib/python3.10/lib-dynload
Py_GetPythonHome is /usr/bin/..
'3.10.5 (main, Jun  8 2022, 09:26:22) [GCC 11.3.0]'
'/usr/bin/Natron'
'/usr/bin/..'
'/usr/bin/..'
'lib'
'/usr/bin/Natron'
'/usr/bin/..'
'/usr/bin/..'
  sys.path = [
    '/home/marillat',
    '/usr/lib/python3.10',
    '/usr/lib/python3.10/lib-dynload',
    '/usr/lib/python310.zip',
    '/usr/local/lib/python3.10/dist-packages',
    '/usr/lib/python3/dist-packages',
    '/usr/lib/python3.10/dist-packages',
  ]
  sys.version =   sys._base_executable =   sys.base_prefix =   sys.base_exec_prefix =   sys.platlibdir =   sys.executable =   sys.prefix =   sys.exec_prefix = <string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
<string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
Python library is in /usr/lib/python3/dist-packages
XXX lineno: 110, opcode: 48
Traceback (most recent call last):
  File "signature_bootstrap.py", line 110, in bootstrap
SystemError: unknown opcode
Fatal Python error: init_phase_2: could not initialize part 2
Python runtime state: initialized

Current thread 0x00007f9d49f33a40 (most recent call first):
  File "/usr/lib/python3/dist-packages/shiboken2/__init__.py", line 30 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 883 in exec_module
  File "<frozen importlib._bootstrap>", line 688 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "/usr/lib/python3/dist-packages/PySide2/__init__.py", line 58 in _setupQtDirectories
  File "/usr/lib/python3/dist-packages/PySide2/__init__.py", line 107 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 883 in exec_module
  File "<frozen importlib._bootstrap>", line 688 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 992 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 776 in create_module
  File "<frozen importlib._bootstrap>", line 571 in module_from_spec
  File "<frozen importlib._bootstrap>", line 674 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "<string>", line 3 in <module>

Extension modules: shiboken2.shiboken2 (total: 1)
zsh: IOT instruction (core dumped)  Natron
```

**Comment by rodlie** [comment]
Looks like a Python issue.

Please add more info, like Qt version used and distro etc.

**Comment by marillat** [comment]
May be related to https://bugs.debian.org/1008849
I'm doing new pyside2/shiboken2 packages to be sure.

**Comment by marillat** [comment]
The bug is still here but with less errors
How I can debug that ?
```
$ LANG=C  Natron
Natron Version 2.5
(C) 2018-2022 The Natron developers
(C) 2013-2018 INRIA and Alexandre Gauthier-Foichat
>>>Use the --help or -h option to print usage.<<<
args:
* Command-line parsing results:
clearCacheOnLaunch: false
clearOpenFXCacheOnLaunch: false
useDefaultSettings: false
isBackground: false
isInterpreterMode: false
enableRenderStats: false
exportDocsPath: ""
ipcPipe: ""
defaultOnProjectLoadedScript: ""
settingCommands:
pythonCommands:
writers:
readers:
atLeastOneOutput: false
filename: ""
rangeSet: false
frameRanges:
* End of command-line parsing results.
argv[0] = Natron
keyboard input locale: "en"
Fontconfig configuration file /usr/bin/../Resources/etc/fonts does not exist, not setting FONTCONFIG_PATH 
"/usr/bin/../lib/python310.zip" does not exist, not added to PYTHONPATH
"/usr/bin/../lib/python3.10/site-packages" does not exist, not added to PYTHONPATH
"/usr/bin/../Plugins" does not exist, not added to PYTHONPATH
Py_SetPythonHome("/usr/bin/..")
PYTHONPATH set to /usr/bin/../lib/python3.10:/usr/bin/../lib/python3.10/lib-dynload
Py_Initialize()
PATH is /home/marillat/bin:/sbin:/usr/sbin:/home/marillat/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/games
PYTHONPATH is /usr/bin/../lib/python3.10:/usr/bin/../lib/python3.10/lib-dynload
PYTHONHOME is (null)
Py_DebugFlag is 0
Py_VerboseFlag is 0
Py_InteractiveFlag is 0
Py_InspectFlag is 0
Py_OptimizeFlag is 0
Py_NoSiteFlag is 0
Py_BytesWarningFlag is 0
Py_FrozenFlag is 0
Py_HashRandomizationFlag is 1
Py_IsolatedFlag is 0
Py_QuietFlag is 0
Py_IgnoreEnvironmentFlag is 0
Py_DontWriteBytecodeFlag is 0
Py_NoUserSiteDirectory is 1
Py_GetProgramName is Natron
Py_GetPrefix is /usr/bin/..
Py_GetExecPrefix is /usr/bin/..
Py_GetProgramFullPath is /usr/bin/Natron
Py_GetPath is /usr/bin/../lib/python3.10:/usr/bin/../lib/python3.10/lib-dynload:/usr/bin/../lib/python310.zip:/usr/bin/../lib/python3.10:/usr/bin/../lib/python3.10/lib-dynload
Py_GetPythonHome is /usr/bin/..
'3.10.5 (main, Jun  8 2022, 09:26:22) [GCC 11.3.0]'
'/usr/bin/Natron'
'/usr/bin/..'
'/usr/bin/..'
'lib'
'/usr/bin/Natron'
'/usr/bin/..'
'/usr/bin/..'
  sys.path = [
    '/home/marillat',
    '/usr/lib/python3.10',
    '/usr/lib/python3.10/lib-dynload',
    '/usr/lib/python310.zip',
    '/usr/local/lib/python3.10/dist-packages',
    '/usr/lib/python3/dist-packages',
  ]
  sys.version =   sys._base_executable =   sys.base_prefix =   sys.base_exec_prefix =   sys.platlibdir =   sys.executable =   sys.prefix =   sys.exec_prefix = <string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
<string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
Python library is in /usr/lib/python3/dist-packages
Natron: AppManager.cpp:2992: void Natron::AppManager::initPython(): Assertion `ok' failed.
zsh: IOT instruction (core dumped)  LANG=C Natron
```

**Comment by marillat** [comment]
Qt 5.15.2
python 3.10
amd64

Here is the backtrace
```
Thread 1 "Natron" received signal SIGABRT, Aborted.
0x00007ffff585f8a1 in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff585f8a1 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff5849546 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff584942f in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff5858222 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x0000555555ba2c77 in Natron::AppManager::initPython (this=0x7fffffffde50) at AppManager.cpp:2992
#5  0x0000555555b9454f in Natron::AppManager::loadFromArgs (this=0x7fffffffde50, cl=...) at AppManager.cpp:379
#6  0x0000555555b94863 in Natron::AppManager::load (this=0x7fffffffde50, argc=1, argv=0x7fffffffdfa8, cl=...) at AppManager.cpp:415
#7  0x0000555555694631 in main (argc=1, argv=0x7fffffffdfa8) at NatronApp_main.cpp:146
```

**Comment by rodlie** [comment]
Are you able to use Python 3.9?

A quick search online seems to indicate that Qt/PySide 5.15.2 does not support Python 3.10 properly(?).

**Comment by marillat** [comment]
I can't use python 3.9 as pyside2 packages have cpython extension build with python 3.10
Otherwise pyside2 build fine with python 3.10 as Debian add patches https://salsa.debian.org/qt-kde-team/qt/pyside2/-/tree/master/debian/patches

**Comment by rodlie** [comment]
Yeah, something is broken in the Debian version you are using, can't help much with that.

Not an Natron issue so will close.

*For reference I'm able to build and run Natron RB-2.5 on Ubuntu 22.04 (python 3.10/qt 5.15.3).*
